### PR TITLE
Add a section about how git works

### LINKED ISSUE #1: It would be nice to have some resources on how git works
It would be nice to include a section that links to some resources on how git works.

### PR DESCRIPTION
**Pull request by jar349**
Closes #1

This PR adds a section that includes links for readers to learn how git works.  It includes a link to a free book and a YouTube video from Scott Chacon, who I believe should be regarded as a git expert.

### CODE REVIEW

**Review by aweinert-MIT — APPROVED** [review]
I have watched the video and think it is good.

**Comment by aweinert-MIT** [comment]
Perhaps we can an image linking to the video as well so it the README just isn't a wall of text?

**Comment by jar349** [comment]
go ahead!

**Comment by aweinert-MIT** [comment]
Will add image referencing video in a future PR

**Pull request merged**
